-- DDL SCRIPTS TO CREATE SCHEMA FROM SCRATCH

DROP TABLE IF EXISTS TABLEAU_USER.TDS_DATASOURCES;
DROP TABLE IF EXISTS TABLEAU_USER.TDS_COLUMNS;
DROP TABLE IF EXISTS TABLEAU_USER.TDS_RELATIONS;
DROP TABLE IF EXISTS TABLEAU_USER.TDS_FOLDERS;
DROP TABLE IF EXISTS TABLEAU_USER.TDS_DRILL_PATHS;


CREATE TABLE TABLEAU_USER.TDS_DATASOURCES
(
	DATASOURCE_ID			INTEGER,
	DATASOURCE_NAME			VARCHAR(255),
	DATASOURCE_CAPTION		VARCHAR(255),
	DATASOURCE_REPO_ID		VARCHAR(255)
)
;

CREATE TABLE TABLEAU_USER.TDS_COLUMNS
(
	DATASOURCE_ID			INTEGER,
	COLUMN_NAME				VARCHAR(255),
	COLUMN_CAPTION			VARCHAR(255),
	COLUMN_DATATYPE			VARCHAR(255),
	COLUMN_ROLE				VARCHAR(255),
	COLUMN_TYPE				VARCHAR(255),
	COLUMN_AGGREGATION		VARCHAR(255),
	COLUMN_HIDDEN			BOOLEAN,
	CALCULATION_CLASS		VARCHAR(255),
	CALCULATION_FORMULA		VARCHAR(3000),
	DB_TABLE				VARCHAR(255),
	DB_COLUMN				VARCHAR(255),
	FORMATTED_TEXT			VARCHAR(10000)
)
;

CREATE TABLE TABLEAU_USER.TDS_RELATIONS
(
	DATASOURCE_ID			INTEGER,
	RELATION_NAME			VARCHAR(255),
	RELATION_TYPE			VARCHAR(255),
	RELATION_TEXT			VARCHAR(3000)
)
;


CREATE TABLE TABLEAU_USER.TDS_FOLDERS
(
	DATASOURCE_ID			INTEGER,
	FOLDER_NAME				VARCHAR(255),
	FOLDER_ROLE				VARCHAR(255),
	FOLDER_ITEM_NAME		VARCHAR(255),
	FOLDER_ITEM_TYPE		VARCHAR(255)
)
;


CREATE TABLE TABLEAU_USER.TDS_DRILL_PATHS
(
	DATASOURCE_ID			INTEGER,
	DRILL_PATH_NAME			VARCHAR(255),
	COLUMN_NAME				VARCHAR(255),
	DRILL_PATH_ORDER		INTEGER
)
;


GRANT ALL ON TABLEAU_USER.TDS_DATASOURCES TO MLAHOYA, VBURETEA, BLAPIERRE, ADEMIRCI, BABONAM, DTEO;
GRANT ALL ON TABLEAU_USER.TDS_COLUMNS TO MLAHOYA, VBURETEA, BLAPIERRE, ADEMIRCI, BABONAM, DTEO;
GRANT ALL ON TABLEAU_USER.TDS_FOLDERS TO MLAHOYA, VBURETEA, BLAPIERRE, ADEMIRCI, BABONAM, DTEO;
GRANT ALL ON TABLEAU_USER.TDS_RELATIONS TO MLAHOYA, VBURETEA, BLAPIERRE, ADEMIRCI, BABONAM, DTEO;
GRANT ALL ON TABLEAU_USER.TDS_DRILL_PATHS TO MLAHOYA, VBURETEA, BLAPIERRE, ADEMIRCI, BABONAM, DTEO;
